### ISSUE TITLE
missing crypto_deterministic_config example to re-identify

### ISSUE THREAD

**Issue by hilliao** [googleapis/python-dlp#108]
I don't see an example of https://youtu.be/h0BnA7R8vg4?t=99 which shows the recommended way to de-identify by encrypting the sensitive data. A search of crypto_deterministic_config shows no sample code snippets. I checked [the Node js sample](https://github.com/googleapis/nodejs-dlp/tree/master/samples) and did not see any example of  [CryptoDeterministicConfig](https://cloud.google.com/dlp/docs/reference/rest/v2/projects.deidentifyTemplates#cryptodeterministicconfig) either. Are there plans to create sample code used to produce the [KittyCat Walks](https://youtu.be/h0BnA7R8vg4?t=99) credit card example?

ref: https://cloud.google.com/dlp/docs/deidentify-sensitive-data#dlp-deidentify-fpe-python

**Comment by busunkim96** [comment]
@rogerthatdev Would you know if there any plans to create a DLP sample like this?
