### ISSUE TITLE
Unable to install google-cloud-dlp in AI Platform with custom prediction

### ISSUE THREAD

**Issue by gogasca** [googleapis/python-dlp#11]
#### Environment details

  - OS type and version: AI Platform prediction
  - Python version:  Python 3.7
  - `google-cloud-dlp` version: 0.13.0

#### Steps to reproduce

To reproduce:
1. Pass in setup.py (google-cloud-dlp) OR
2. Pass the .tar.gz install file:

```
gcloud beta ai-platform versions create {MODEL1_VERSION} \
    --model {MODEL_NAME} \
    --origin gs://{BUCKET_NAME}/{MODEL_DIR} \
    --runtime-version 1.15 \
    --python-version 3.7 \
    --package-uris gs://{BUCKET_NAME}/{PACKAGES_DIR}/sentiment_classifier_dlp-0.1.tar.gz,gs://{BUCKET_NAME}/google-cloud-dlp-0.13.0.tar.gz \
    --prediction-class=custom_prediction.CustomModelPrediction \
    --service-account {SA_NAME}@{PROJECT}.iam.gserviceaccount.com   
```

I get: `{'error': 'Prediction failed: unknown error.'} `
In logs:
```
ERROR:root:Prediction failed: The 'google-cloud-dlp' distribution was not found and is required by the application
Expand all | Collapse all{
 insertId: "5e8e5528000a21fcbfddb3fb"  
 logName: "projects/news-ml-257304/logs/ml.googleapis.com%2Fprimary.stderr"  
 receiveTimestamp: "2020-04-08T22:50:17.008478460Z"  
 resource: {
  labels: {…}   
  type: "cloudml_model_version"   
 }
 textPayload: "ERROR:root:Prediction failed: The 'google-cloud-dlp' distribution was not found and is required by the application"  
 timestamp: "2020-04-08T22:50:16.664060Z"  
}
```
#### Stack trace

```
The 'google-cloud-dlp' distribution was not found and is required by the application"  
```

#### Workaround:

Seems to be a problem for `pkg_resources.get_distribution` when executed it returns an error: "distribution was not found and is required by the application"

1) To be able to install it:

a) I replaced _GAPIC_LIBRARY_VERSION in this [line](https://github.com/googleapis/python-dlp/blob/master/google/cloud/dlp_v2/gapic/dlp_service_client.py#L44)

```
_GAPIC_LIBRARY_VERSION = pkg_resources.get_distribution("google-cloud-dlp").version
```

with
```
_GAPIC_LIBRARY_VERSION = '0.13.1'
```
* Im using 0.13.1 instead of 0.13.0 just for tracking purposes.

b) Rebuild the library using `python setup.py sdist`. 
c) Uploaded .tar.gz to the GCS bucket and define this value under --package-uris when creating the model version. Working sample: gs://news-ml-experiments/google-cloud-dlp-0.13.1.tar.gz

The way AI Platform Prediction install libraries is via:

```
python -m pip install --target=/tmp/custom_lib --no-cache-dir -b /tmp/pip_builds /tmp/custom_code/google-cloud-dlp-0.13.0.tar.gz
```
I assume `pkg_resources.get_distribution` may not have visibility of this when module is installed via `pip install -t`

https://github.com/pypa/setuptools/blob/53c284b325959a6fd177e9d37d8b5dd5824db2b3/pkg_resources/__init__.py#L355

**Comment by busunkim96** [comment]
None of the options used in the install command strike me as ones that would change the visibility of the package to `pkg_resources`.  `-t` 

Is there anything else interesting about how AI Platform installs these packages?

**Comment by puneith** [comment]
@busunkim96 do we have any update on this? Are you still looking for inputs on how AI Platform installs packages?

**Comment by vchudnov-g** [comment]
@gogasca Is this problem still occurring?

**Comment by gogasca** [comment]
TBH I don't know this is a very old issue :) ok to close.
