### ISSUE TITLE
Samples that depend on BigQuery are not yet compatible with Python 3.10

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-dlp#277]
`google-cloud-bigquery` does not yet support Python 3.10. When it does, the 3.10 samples check should turn green. For now, it is OK to merge PRs with a failing 3.10 samples check (the status check is intentionally optional). 

See https://github.com/googleapis/python-bigquery/issues/1006 for the status of python 3.10 support.

**Comment by leahecole** [comment]
hoping #284 will fix this
