### ISSUE TITLE
Unable to use python DLP on M1.

### ISSUE THREAD

**Issue by gso-pickstar** [googleapis/python-dlp#316]
Hey all,

Am attempting to do some local development with Python DLP on an M1 Mac, and am running into an issue with the `grpc` `cygrpc` library that is shipped for OSX.

It's an `x86_64` architecture shared library, but we need an `arm64e` architecture shared library for M1 macs.

Are there any plans to make this compatible?

#### Environment details

  - OS type and version: M1, macOS Monterey 12.1
  - Python version: Python 3.10.0
  - pip version: pip 21.3.1 
  - `google-cloud-dlp` version: 3.5.0

#### Steps to reproduce

  1. Create a virtual environment using Pipenv.
  2. Attempt to use DlpServiceClient in python code running on an M1 device.

#### Code example

```ini
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
google-cloud-dlp = "3.5.0"

[dev-packages]

[requires]
python_version = "3.10"
```

```python
from google.cloud.dlp import DlpServiceClient

dlp = DlpServiceClient()
dlp.deidentify_content(
    request={
        "parent": f"data-{environment}",
        "deidentify_config": deidentify_config,
        "inspect_config": inspect_config,
        "item": item,
    }
)
```

#### Stack trace
```
ImportError: dlopen(/Users/XXX/.local/share/virtualenvs/marketplace-WSB_kZMA/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/XXX/.local/share/virtualenvs/XXX-WSB_kZMA/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-310-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)
```

**Comment by busunkim96** [comment]
Hi @gso-pickstar,

It looks like this issue is described in https://github.com/grpc/grpc/issues/28387.

The most [recent comment](https://github.com/grpc/grpc/issues/28387#issuecomment-1016166913) has a workaround for installing the package from source (ignoring the wheel, which is not compatible).

Since this issue is for the grpcio package specifically, I'm going to close this issue in favor of tracking there.
